# Generated by Django 5.1.15 on 2026-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('data_treatment_accepted', models.BooleanField(default=False)),
                ('entity', models.CharField(max_length=255)),
                ('chosen_modality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('attendance_commitment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=100)),
                ('modality', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Ambas', 'Ambas')], max_length=20)),
                ('enrollment_start', models.DateTimeField()),
                ('enrollment_end', models.DateTimeField()),
                ('class_start_date', models.DateField()),
                ('class_end_date', models.DateField(blank=True, null=True)),
                ('schedule_details', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
