# Generated by Django 5.1.15 on 2026-09-15 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='attendance_commitment',
            field=models.BooleanField(default=False, verbose_name='Compromiso de asistencia'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='chosen_modality',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=50, verbose_name='Modalidad elegida'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='data_treatment_accepted',
            field=models.BooleanField(default=False, verbose_name='Autorización de tratamiento de datos'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='entity',
            field=models.CharField(max_length=255, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollments.module', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='module',
            name='class_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin de clases'),
        ),
        migrations.AlterField(
            model_name='module',
            name='class_start_date',
            field=models.DateField(verbose_name='Fecha de inicio de clases'),
        ),
        migrations.AlterField(
            model_name='module',
            name='enrollment_end',
            field=models.DateTimeField(verbose_name='Fin de inscripciones'),
        ),
        migrations.AlterField(
            model_name='module',
            name='enrollment_start',
            field=models.DateTimeField(verbose_name='Inicio de inscripciones'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='modality',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Ambas', 'Ambas')], max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='module',
            name='schedule_details',
            field=models.CharField(max_length=255, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(max_length=100, verbose_name='Semestre'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_enrollment_per_user_module'),
        ),
    ]
