# Generated by Django 5.1.15 on 2026-09-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_enrollment_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='locality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localidad o comuna'),
        ),
    ]
