# Generated by Django 5.1.15 on 2026-09-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollment_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='other_entity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otra entidad'),
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Nivel del módulo'),
        ),
    ]
