# Generated by Django 5.1.15 on 2026-09-15 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuario'},
        ),
        migrations.AlterModelOptions(
            name='usersaveddefaults',
            options={'verbose_name': 'Valores predeterminados de usuario', 'verbose_name_plural': 'Valores predeterminados de usuario'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=50, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_business',
            field=models.BooleanField(default=False, verbose_name='Tiene negocio propio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte')], max_length=50, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usersaveddefaults',
            name='last_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Última ciudad'),
        ),
        migrations.AlterField(
            model_name='usersaveddefaults',
            name='last_entity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Última entidad'),
        ),
        migrations.AlterField(
            model_name='usersaveddefaults',
            name='last_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Último barrio'),
        ),
        migrations.AlterField(
            model_name='usersaveddefaults',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_defaults', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
