# Generated by Django 5.1.15 on 2026-09-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico alternativo'),
        ),
        migrations.AddField(
            model_name='usersaveddefaults',
            name='last_locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Última localidad o comuna'),
        ),
    ]
