# Generated by Django 5.1.15 on 2026-09-19 05:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_alternate_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Profesional', 'Profesional'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Ninguna de las anteriores', 'Ninguna de las anteriores')], max_length=100, null=True, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Teléfono celular'),
        ),
    ]
